### ISSUE TITLE
大佬请问，当我把PHP-Apache改成PHP-Nginx的时候，init.sh里面要改成什么呢？

### ISSUE THREAD

**Issue by 0liragunse** [locoz666/discuz-x-container#2]
当我把https://github.com/locoz666/discuz-x-container/blob/main/Dockerfile里面的 `FROM php:7-apache`  改成 `FROM webdevops/php-nginx:7.4` 之后，

https://github.com/locoz666/discuz-x-container/blob/main/init.sh 的最后一行 `/usr/local/bin/apache2-foreground` 需要改写成什么呢？

**Comment by locoz666** [comment]
文件中有注释说明，就是php:7-apache原本的启动流程，你直接看你要换的上层镜像的Dockerfile就知道了

**Comment by 0liragunse** [comment]
好的 谢谢大佬
